name: CI Tests

on:
  pull_request:

jobs:
  ci-mistral:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Install CosmoCC
        run: |
          mkdir -p cosmocc
          cd cosmocc
          wget https://cosmo.zip/pub/cosmocc/cosmocc.zip
          unzip cosmocc.zip
          cd ..
          ls
          ./cosmocc/bin/make -j8 && ./cosmocc/bin/make install

      - name: Create LLM Executable
        run: |
          curl -o mistral.gguf -L https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q4_K_M.gguf
          cat > .args <<EOL
          -m
          mistral.gguf
          ... 
          EOL
          cp /usr/local/bin/llamafile llamafile_exe
          chmod +x llamafile_exe
          zipalign -j0 \
            llamafile_exe \
            mistral.gguf \
            .args

      - name: Execute LLM
        run: |
          ./llamafile_exe --temp 0.7 --n-predict 50 -p '[INST]Write a story about llamas[/INST]'
