   name: ci tests

   on:
     pull_request:

   jobs:
    build:
      runs-on: macos-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: build application
        run: make -j8
