   name: ci tests

   on:
     pull_request:

   jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: install make
        run: brew install make
      - name: build application
        run: make -j8
